
# This file is autogenerated by update.py

@ stub -version=0x602+ RoActivateInstance
@ cdecl -version=0x600+ RoGetActivationFactory(ptr long ptr) msvcrt.RoGetActivationFactory
@ stub -version=0x602+ RoGetApartmentIdentifier
@ stub -version=0x602+ RoInitialize
@ stub -version=0x602+ RoRegisterActivationFactories
@ stub -version=0x602+ RoRegisterForApartmentShutdown
@ stub -version=0x602+ RoRevokeActivationFactories
@ stub -version=0x602+ RoUninitialize
@ stub -version=0x602+ RoUnregisterForApartmentShutdown
